Add registry and SkyDB to docs for nodejs
SkynetLabs/skynet-docs pull request #28
Opened 2022-06-24 20:38 UTC by m-cat

# PULL REQUEST

## Overview

User noticed these docs were missing, although they are available now with `v2.6.0`.

2022-06-27 12:37 UTC, kwypchlo requested changes

2022-06-27 12:37 UTC, kwypchlo commented on source/includes/_registry.md
> +    revision: 0
```suggestion
    revision: 0n
```

2022-06-27 12:37 UTC, kwypchlo commented on source/includes/_registry.md
> +    data: "bar",
isn't `data` an `Uint8Array` ?

2022-06-27 12:37 UTC, kwypchlo commented on source/includes/_registry.md
> +    revision: 0
```suggestion
    revision: 0n
```

2022-06-27 12:37 UTC, interstella-5555 commented on source/includes/_registry.md
> +const revision = 0;
```suggestion
const revision = BigInt(0);
```

2022-06-27 12:37 UTC, kwypchlo commented on source/includes/_registry.md
> +}
```suggestion
(async () => {
  const url = await client.registry.getEntryUrl(publicKey, dataKey);
})();
```

2022-06-27 12:37 UTC, kwypchlo commented on source/includes/_registry.md
> +}
Any reason to wrap this in a function with throw-catch ? I think the example should be as simple as possible like

```suggestion
const url = client.registry.getEntryUrl(publicKey, dataKey);
```

2022-06-27 12:37 UTC, kwypchlo commented on source/includes/_registry.md
> +}
```suggestion
(async () => {
  await client.registry.setEntry(privateKey, entry);
})();
```

2022-06-27 12:37 UTC, kwypchlo commented on source/includes/_registry.md
> +}
```suggestion
(async () => {
  const { entry, signature } = await client.registry.getEntry(publicKey, dataKey);
})();
```

2022-06-27 12:37 UTC, kwypchlo commented on source/includes/_skydb.md
> +}
```suggestion
(async () => {
  const { data, dataLink } = await client.db.getJSON(publicKey, dataKey);
})();
```

2022-06-27 12:37 UTC, kwypchlo commented on source/includes/_skydb.md
>  }
```suggestion
(async () => {
  await client.db.setJSON(privateKey, dataKey, json);
})();
```

2022-06-27 12:37 UTC, kwypchlo commented on source/v4/includes/_registry.md
> +}
```suggestion
(async () => {
  const { entry, signature } = await client.registry.getEntry(publicKey, dataKey);
})();
```

2022-06-27 12:37 UTC, kwypchlo commented on source/v4/includes/_registry.md
> +    revision: 0
```suggestion
    revision: 0n
```

2022-06-27 12:37 UTC, interstella-5555 commented on source/v4/includes/_registry.md
> +    data: "bar",
AFAIK this is a Uint8Array

2022-06-27 12:37 UTC, interstella-5555 commented on source/v4/includes/_registry.md
> +}
```suggestion
(async () => {
  await client.registry.setEntry(privateKey, entry);
})();
```

2022-06-27 12:37 UTC, kwypchlo commented on source/v4/includes/_registry.md
> +const revision = 0;
```suggestion
const revision = BigInt(0);
```

2022-06-27 12:37 UTC, interstella-5555 commented on source/v4/includes/_registry.md
> +const data = "bar";
it can be a string or only Uint8Array ?

2022-06-27 12:37 UTC, kwypchlo commented on source/v4/includes/_registry.md
> +}
Any reason to wrap this in a function with throw-catch ? I think the example should be as simple as possible like

```suggestion
const url = client.registry.getEntryUrl(publicKey, dataKey);
```

2022-06-27 12:37 UTC, kwypchlo commented on source/v4/includes/_registry.md
> +}
```suggestion
(async () => {
  const url = await client.registry.getEntryUrl(publicKey, dataKey);
})();
```

2022-06-27 12:37 UTC, kwypchlo commented on source/v4/includes/_skydb.md
> +}
```suggestion
(async () => {
  const { data, dataLink } = await client.db.getJSON(publicKey, dataKey);
})();
```

2022-06-27 12:37 UTC, kwypchlo commented on source/v4/includes/_skydb.md
>  }
```suggestion
(async () => {
  await client.db.setJSON(privateKey, dataKey, json);
})();
```

2022-07-05 12:07 UTC, kwypchlo approved these changes, later dismissed

2022-07-06 08:18 UTC, ro-tex approved these changes

2022-07-06 08:20 UTC, kwypchlo approved these changes

2022-07-06 13:51 UTC, dghelm approved these changes
Looks good! Much needed refresh on latest features.

Follow up note: we should probably add tryFiles details to uploading a directory and link to docs for more information: https://docs.skynetlabs.com/skynet-topics/framework-flexible-routing

2022-07-06 13:55 UTC, m-cat commented
@dghelm Thanks, wrote up an issue!

https://linear.app/skynetlabs/issue/SKY-1238/add-tryfiles-details-to-docs

2022-07-06 13:57 UTC, merged